version: "3.8"
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./citizens-book-backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
  front:
    depends_on:
      - app
    build: ./citizens-book-frontend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8080:8080"
volumes:
  db: